version: "3"

services:

  shopware:
    # use either tag "latest" or any other version like "6.1.5", ...
    image: dockware/dev:6.4.20.2
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
      - "./src/custom/plugins/PackiroPayment:/var/www/html/custom/plugins/PackiroPayment"
      - "./src/custom/plugins/PackiroConfigurator:/var/www/html/custom/plugins/PackiroConfigurator"
      - "./src/custom/plugins/PackiroCore:/var/www/html/custom/plugins/PackiroCore"
      - "./src/custom/plugins/PackiroVatValidator:/var/www/html/custom/plugins/PackiroVatValidator"
      - "./src/custom/plugins/PackiroCheckout:/var/www/html/custom/plugins/PackiroCheckout"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.1

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false